### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by hughcameron** [Trunkplatform/lpma#18]
We're keen to improve the quality of background images on the site. Currently the resolution appears grainy. I've tested down scaling the images in Contentful but this doesn't appear to provide a resolution. 

Can this be solved with a Netlify setting or by installing a Gatsby plugin to handle image loading, perhaps this: https://www.gatsbyjs.org/packages/gatsby-image/?

**Comment by hughcameron** [comment]
Hey @mattyvent

**Comment by gnunua** [comment]
Hey @hughcameron. 
Here is a unique  page for testing image quality in a different variety 

https://quirky-raman-fdadf9.netlify.com/image-test/

**Comment by gnunua** [comment]
Hey @hughcameron. I have changed the approach to handling images. now in LPMA, we are using Lazy-loading images.
 
Lazy-loading images or loading smaller-sized placeholders has become a standard way of improving the overall UX of a site. Facebook began using it as a technique to fix the jarring, jittery problem of a solid background suddenly transforming into an image. Medium also uses blurred images to preserve the layout of the site so that images don’t bump text or other DOM elements farther down the page as the images load.
